/**
 * PowPeg federate JVM runner.
 *
 * Ported from rootstock-integration-tests' `lib/federate-runner.js` +
 * `lib/federate-starter.js` + the genesis slice of
 * `config/regtest-all-keyfiles.js`. Spawns
 *
 *   java -Drsk.conf.file=<conf> -cp <powpegFatJar> \
 *        co.rsk.federate.FederateRunner --regtest
 *
 * Differences from the single-rskj-node runner ({@link spawnRskjNode}):
 *
 *   - Different main class (`co.rsk.federate.FederateRunner`) and a
 *     different fat JAR (`federate-node-*-all.jar`).
 *   - A federate signs Bridge transactions with a key file and joins the
 *     genesis federation; we materialise the member's private key as a
 *     0400 key file (PowPeg refuses group/world-readable keys) and point
 *     all three signer slots (BTC/RSK/MST) at it, exactly as RIT does.
 *   - Teardown is SIGKILL, not SIGTERM-then-SIGKILL: the federate JVM
 *     does not handle SIGTERM reliably (RIT's runner notes the same).
 *
 * Config strategy: rather than RIT's static `fedN.conf` + a long list of
 * `-D` overrides (which forces `peer.active.0.ip` indexed-key soup that
 * HOCON treats as an object, not a list), we generate ONE complete HOCON
 * file per federate with `peer.active` as a real list. `-Drsk.conf.file`
 * layers it over rskj's `--regtest` base via HOCON `withFallback`, so a
 * partial `miner { ... }` block merges with regtest's (keeping its
 * coinbase secret) rather than replacing it.
 */

import { spawn, type ChildProcess } from "node:child_process";
import { chmodSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import {
  ALL_FORKS,
  type GenesisFederationMember,
  GENESIS_FEDERATION,
  peerActiveWiring,
} from "./federation/genesis-federation.js";
import { waitForPort } from "./port-utils.js";
import { waitForRpcReady } from "./rpc-readiness.js";

const DEFAULT_JAVA = process.env.JAVA_BIN_PATH ?? "java";

/** Federates ignore SIGTERM; we go straight to SIGKILL after this wait. */
const SHUTDOWN_GRACE_MS = 5_000;

/** The nine RPC modules RIT enables on every federate (all v1.0). */
const RPC_MODULES = ["eth", "net", "rpc", "web3", "evm", "mnr", "personal", "fed", "rsk"] as const;

export interface FederateConfig {
  /** Absolute path to the powpeg `federate-node-*-all.jar`. */
  jarPath: string;
  /** Which genesis federation member this process is. */
  member: GenesisFederationMember;
  /** `host:port` of the bitcoind the federate watches (its BTC peer). */
  bitcoinPeerAddress: string;
  /** All federation members, for `peer.active` mesh wiring. Defaults to all three. */
  allMembers?: readonly GenesisFederationMember[];
  /** Data dir. Fresh tmpdir when omitted (removed on stop). */
  dataDir?: string;
  keepDataDir?: boolean;
  jvmArgs?: string[];
  log?: (line: string) => void;
  /** Readiness timeout (ms). Default 60s. */
  readinessTimeoutMs?: number;
}

export interface FederateRunnerHooks {
  spawnFn?: typeof spawn;
  mkdirFn?: (p: string) => void;
  mkdtempFn?: (prefix: string) => string;
  writeFileFn?: (p: string, contents: string) => void;
  chmodFn?: (p: string, mode: number) => void;
  rmFn?: (p: string) => void;
  waitForPortFn?: typeof waitForPort;
  waitForRpcReadyFn?: typeof waitForRpcReady;
  javaBin?: string;
}

export interface FederateHandle {
  id: string;
  rpcUrl: string;
  rpcPort: number;
  p2pPort: number;
  dataDir: string;
  pid: number | null;
  ready(): Promise<void>;
  stop(): Promise<void>;
}

/**
 * Render the complete HOCON config for one federate. Exported so unit
 * tests can assert the generated config without spawning a JVM.
 */
export function renderFederateConfig(input: {
  member: GenesisFederationMember;
  keyFilePath: string;
  bitcoinPeerAddress: string;
  dataDir: string;
  allMembers?: readonly GenesisFederationMember[];
}): string {
  const { member, keyFilePath, bitcoinPeerAddress, dataDir } = input;
  const peers = peerActiveWiring(member, input.allMembers ?? GENESIS_FEDERATION);
  // peerActiveWiring returns flat dotted keys; reshape into list entries.
  const peerCount = Object.keys(peers).filter((k) => k.endsWith(".ip")).length;
  const peerEntries: string[] = [];
  for (let i = 0; i < peerCount; i++) {
    peerEntries.push(
      `        { ip = "${peers[`peer.active.${i}.ip`]}", ` +
        `port = ${peers[`peer.active.${i}.port`]}, ` +
        `nodeId = "${peers[`peer.active.${i}.nodeId`]}" }`,
    );
  }
  const modules = RPC_MODULES.map(
    (name) => `        { name = "${name}", version = "1.0", enabled = "true" }`,
  ).join(",\n");
  const forkHeights = ALL_FORKS.map((fork) => `        ${fork} = 1`).join("\n");

  return `# Generated by rskj-regression orchestrator — federate ${member.id}
peer {
    privateKey = "${member.privateKey}"
    port = ${member.p2pPort}
    discovery.enabled = false
    networkId = 7771
    active = [
${peerEntries.join(",\n")}
    ]
}

federator {
    enabled = true
    bitcoinPeerAddresses = [ "${bitcoinPeerAddress}" ]
    gasPrice = 1000
    updateBridgeTimerEnabled = false
    amountOfHeadersToSend = 500
    signers {
        BTC {
            type = "keyFile"
            path = "${keyFilePath}"
            bookkeeping {
                difficultyTarget = 3
                informerInterval = 8000
                maxAmountBlockHeaders = 100
                maxChunkSizeToHsm = 100
            }
        }
        RSK { type = "keyFile", path = "${keyFilePath}" }
        MST { type = "keyFile", path = "${keyFilePath}" }
    }
}

miner {
    client.enabled = false
    server.enabled = true
}

rpc {
    providers.web.http {
        enabled = true
        host = "0.0.0.0"
        port = ${member.rpcPort}
        cors = "*"
        hosts = [ "*" ]
    }
    providers.web.ws.enabled = false
    modules = [
${modules}
    ]
}

database {
    dir = "${join(dataDir, "db")}"
    reset = true
}

blockchain.config.hardforkActivationHeights {
${forkHeights}
}
`;
}

/**
 * Spawn one federate. Resolves once the process is spawned and the conf +
 * key file are written; call `handle.ready()` to await RPC availability.
 */
export async function spawnFederate(
  config: FederateConfig,
  hooks: FederateRunnerHooks = {},
): Promise<FederateHandle> {
  const spawnFn = hooks.spawnFn ?? spawn;
  const mkdirFn =
    hooks.mkdirFn ??
    ((p: string): void => {
      mkdirSync(p, { recursive: true });
    });
  const mkdtempFn = hooks.mkdtempFn ?? ((prefix: string): string => mkdtempSync(prefix));
  const writeFileFn =
    hooks.writeFileFn ?? ((p: string, c: string): void => writeFileSync(p, c, "utf8"));
  const chmodFn = hooks.chmodFn ?? ((p: string, mode: number): void => chmodSync(p, mode));
  const rmFn = hooks.rmFn ?? ((p: string): void => rmSync(p, { recursive: true, force: true }));
  const waitForPortFn = hooks.waitForPortFn ?? waitForPort;
  const waitForRpcReadyFn = hooks.waitForRpcReadyFn ?? waitForRpcReady;
  const javaBin = hooks.javaBin ?? DEFAULT_JAVA;
  const log = config.log ?? ((): void => undefined);
  const { member } = config;

  const dataDir = config.dataDir
    ? resolveAndEnsure(config.dataDir, mkdirFn)
    : mkdtempFn(join(tmpdir(), `rskj-regression-${member.id}-`));

  // Materialise the signing key at mode 0400 — PowPeg refuses a
  // group/world-readable key file (`Invalid key file permissions`).
  const keyFilePath = join(dataDir, "signer.key");
  writeFileFn(keyFilePath, `${member.privateKey}\n`);
  chmodFn(keyFilePath, 0o400);

  const configPath = join(dataDir, "federate.conf");
  writeFileFn(
    configPath,
    renderFederateConfig({
      member,
      keyFilePath,
      bitcoinPeerAddress: config.bitcoinPeerAddress,
      dataDir,
      allMembers: config.allMembers,
    }),
  );
  log(`[${member.id}] conf → ${configPath} (rpc ${member.rpcPort}, p2p ${member.p2pPort})`);

  const args: string[] = [
    ...(config.jvmArgs ?? []),
    `-Drsk.conf.file=${configPath}`,
    "-cp",
    config.jarPath,
    "co.rsk.federate.FederateRunner",
    "--regtest",
  ];
  log(`[${member.id}] spawn: ${javaBin} ${args.join(" ")}`);

  const child = spawnFn(javaBin, args, { cwd: dataDir, stdio: ["ignore", "pipe", "pipe"] });
  pipeLines(child, log, member.id);

  const rpcUrl = `http://127.0.0.1:${member.rpcPort}`;
  let stopped = false;
  let exited = false;
  let readyDone = false;
  child.on("exit", (code, signal) => {
    exited = true;
    log(`[${member.id}] exited code=${code} signal=${signal}`);
  });

  const onParentTerminate = (): void => {
    if (!stopped && child.pid) {
      try {
        child.kill("SIGKILL");
      } catch {
        /* ignore */
      }
    }
  };
  process.once("SIGINT", onParentTerminate);
  process.once("SIGTERM", onParentTerminate);
  process.once("beforeExit", onParentTerminate);

  const handle: FederateHandle = {
    id: member.id,
    rpcUrl,
    rpcPort: member.rpcPort,
    p2pPort: member.p2pPort,
    dataDir,
    get pid(): number | null {
      return child.pid && !exited ? child.pid : null;
    },
    async ready(): Promise<void> {
      if (readyDone) return;
      const timeoutMs = config.readinessTimeoutMs ?? 60_000;
      await waitForPortFn(
        { host: "127.0.0.1", port: member.rpcPort },
        { attempts: Math.ceil(timeoutMs / 1000), intervalMs: 1000 },
      );
      await waitForRpcReadyFn(rpcUrl, { timeoutMs, log });
      readyDone = true;
    },
    async stop(): Promise<void> {
      if (stopped) return;
      stopped = true;
      process.removeListener("SIGINT", onParentTerminate);
      process.removeListener("SIGTERM", onParentTerminate);
      process.removeListener("beforeExit", onParentTerminate);
      await killChild(child, log, member.id);
      if (!config.keepDataDir && !config.dataDir) {
        try {
          rmFn(dataDir);
        } catch (err) {
          log(`[${member.id}] failed to remove ${dataDir}: ${(err as Error).message}`);
        }
      }
    },
  };

  return handle;
}

/* -------------------------------------------------------------------------- */

function resolveAndEnsure(p: string, mkdirFn: (p: string) => void): string {
  const abs = resolve(p);
  mkdirFn(abs);
  return abs;
}

function pipeLines(child: ChildProcess, log: (line: string) => void, tag: string): void {
  for (const stream of [child.stdout, child.stderr]) {
    let buf = "";
    stream?.on("data", (chunk: Buffer) => {
      buf += chunk.toString();
      let nl: number;
      while ((nl = buf.indexOf("\n")) !== -1) {
        log(`[${tag}] ${buf.slice(0, nl)}`);
        buf = buf.slice(nl + 1);
      }
    });
  }
}

async function killChild(
  child: ChildProcess,
  log: (l: string) => void,
  tag: string,
): Promise<void> {
  if (child.exitCode !== null || !child.pid) return;
  const exited = new Promise<void>((res) => child.once("exit", () => res()));
  // Federate ignores SIGTERM; give it a short window then SIGKILL.
  try {
    child.kill("SIGTERM");
  } catch {
    return;
  }
  const timer = new Promise<"timeout">((res) =>
    setTimeout(() => res("timeout"), SHUTDOWN_GRACE_MS),
  );
  const outcome = await Promise.race([exited.then(() => "exited" as const), timer]);
  if (outcome === "timeout") {
    log(`[${tag}] SIGTERM ignored; sending SIGKILL`);
    try {
      child.kill("SIGKILL");
    } catch {
      /* ignore */
    }
    await exited;
  }
}
